# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'WorkWithLists' do

  use_frameworks!
  
  # UI
  pod 'SnapKit'
  
  # Network
  pod 'Alamofire'

end
